## Sprint 1 (Importação dos dados)

In [1]:
import pandas as pd

df = pd.read_csv("data/base_varejo.csv", sep=";")

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

Dataframe criado. São 83 mil registros distribuidos em 14 colunas. 4 Colunas estão com nome unnamed e precisão ser exploradas com cuidado.

### Dicionário de dados:
1. DATA: Data da compra;

2. CO_ID: Identificação do número de compra (número da nota fiscal);

3. CL_ID: Identificação do cliente (número do cliente);

4. CL_GENERO: Sexo biológico informado pelo cliente;

5. CL_EC: Estado civil do cliente:
    1: Casado ou união estával;
    2: Divorciado;
    3: Separado;
    4: Solteiro;
    5: Viúvo.

6. CL_FHL: Número de filhos do cliente;

7. CL_SEG: Segmentação econômica do cliente (classe A, B ou C);

8. PR_ID: Código do produto (SKU) adquirido;

9. PR_CAT: Categoria do produto adquirido;

10. PR_NOME: Nome do produto adquirido.

In [3]:
df.head(20)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
5,01/02/2019,1000,534,M,4,1,C,187,HIGIENE,HASTES FLEXIVEIS,NaN,NaN,NaN,NaN
6,01/02/2019,1000,534,M,4,1,C,163,ALIMENTOS,MORTADELA,NaN,NaN,NaN,NaN
7,01/02/2019,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
8,01/02/2019,1000,534,M,4,1,C,95,LIMPEZA,AMACIANTE,NaN,NaN,NaN,NaN
9,01/02/2019,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO,NaN,NaN,NaN,NaN
10,01/02/2019,1000,534,M,4,1,C,182,ALIMENTOS,LATA DE ERVILHA,NaN,NaN,NaN,NaN
11,01/02/2019,1000,534,M,4,1,C,86,HIGIENE,PRESERVATIVO,NaN,NaN,NaN,NaN
12,01/02/2019,1000,534,M,4,1,C,221,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
13,01/02/2019,1000,534,M,4,1,C,200,LIMPEZA,DETERGENTE,NaN,NaN,NaN,NaN
14,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,01/02/2019,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
16,01/02/2019,1000,534,M,4,1,C,84,HIGIENE,PAPEL HIGIENICO,NaN,NaN,NaN,NaN
17,01/02/2019,1000,534,M,4,1,C,121,ALIMENTOS,UVA,NaN,NaN,NaN,NaN
18,01/02/2019,1000,534,M,4,1,C,176,LIMPEZA,LIMPA VIDROS,NaN,NaN,NaN,NaN
19,01/02/2019,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN

In [4]:
df.describe()

,CO_ID,CL_ID,CL_EC,CL_FHL,PR_ID,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
count,830000.00000,830000.000000,830000.000000,830000.00000,830000.000000,0.0,0.0,0.0,0.0
mean,460045.08989,499.595204,2.596911,1.14654,115.051855,NaN,NaN,NaN,NaN
std,265465.24754,287.568253,1.170599,1.41696,66.129241,NaN,NaN,NaN,NaN
min,1000.00000,1.000000,1.000000,0.00000,1.000000,NaN,NaN,NaN,NaN
25%,233117.00000,254.000000,2.000000,0.00000,58.000000,NaN,NaN,NaN,NaN
50%,456517.00000,498.000000,3.000000,0.00000,115.000000,NaN,NaN,NaN,NaN
75%,690132.00000,746.000000,4.000000,2.00000,172.000000,NaN,NaN,NaN,NaN
max,919822.00000,1000.000000,5.000000,4.00000,229.000000,NaN,NaN,NaN,NaN

## Sprint 2 (Transformação de Strings, Integer e Float e Datetime):

In [5]:

#Conversão da DATA para datetime
df['DATA'] = pd.to_datetime(df['DATA'], format='%d/%m/%Y')

In [6]:
# Conversão da colunas IDs para o tipo string (colunas com ID nao tem função matemática e podem acabar gerando viés na análise)
df['CO_ID'] = df['CO_ID'].astype(str)
df['CL_ID'] = df['CL_ID'].astype(str)
df['PR_ID'] = df['PR_ID'].astype(str)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  datetime64[us]
 1   CO_ID        830000 non-null  str
 2   CL_ID        830000 non-null  str
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  str
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: datetime64[us](1), float64(4), int64(2), str(7)
memory usage: 88.7 MB

In [8]:
df.head(20)

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,2019-02-01,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,2019-02-01,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,2019-02-01,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,2019-02-01,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,2019-02-01,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN
5,2019-02-01,1000,534,M,4,1,C,187,HIGIENE,HASTES FLEXIVEIS,NaN,NaN,NaN,NaN
6,2019-02-01,1000,534,M,4,1,C,163,ALIMENTOS,MORTADELA,NaN,NaN,NaN,NaN
7,2019-02-01,1000,534,M,4,1,C,11,ALIMENTOS,AZEITE,NaN,NaN,NaN,NaN
8,2019-02-01,1000,534,M,4,1,C,95,LIMPEZA,AMACIANTE,NaN,NaN,NaN,NaN
9,2019-02-01,1000,534,M,4,1,C,198,BEBIDAS,ENERGETICO,NaN,NaN,NaN,NaN
10,2019-02-01,1000,534,M,4,1,C,182,ALIMENTOS,LATA DE ERVILHA,NaN,NaN,NaN,NaN
11,2019-02-01,1000,534,M,4,1,C,86,HIGIENE,PRESERVATIVO,NaN,NaN,NaN,NaN
12,2019-02-01,1000,534,M,4,1,C,221,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
13,2019-02-01,1000,534,M,4,1,C,200,LIMPEZA,DETERGENTE,NaN,NaN,NaN,NaN
14,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN
15,2019-02-01,1000,534,M,4,1,C,218,ALIMENTOS,BIFE DE COXAO MOLE,NaN,NaN,NaN,NaN
16,2019-02-01,1000,534,M,4,1,C,84,HIGIENE,PAPEL HIGIENICO,NaN,NaN,NaN,NaN
17,2019-02-01,1000,534,M,4,1,C,121,ALIMENTOS,UVA,NaN,NaN,NaN,NaN
18,2019-02-01,1000,534,M,4,1,C,176,LIMPEZA,LIMPA VIDROS,NaN,NaN,NaN,NaN
19,2019-02-01,1000,534,M,4,1,C,13,ALIMENTOS,BANANA,NaN,NaN,NaN,NaN

##

## Sprint 3 (Limpeza de Nulos e Duplicatas):

In [9]:
df.isna().sum()

DATA                0
CO_ID               0
CL_ID               0
CL_GENERO           0
CL_EC               0
CL_FHL              0
CL_SEG              0
PR_ID               0
PR_CAT              0
PR_NOME             0
Unnamed: 10    830000
Unnamed: 11    830000
Unnamed: 12    830000
Unnamed: 13    830000
dtype: int64

As colunas unnamed nao contem dados válidos, podem ser removidas com segurança.

In [10]:
df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"], inplace=True)

In [11]:
df.isna().sum()

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64